version: 3.1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: SteamWebAPI2.sln
  publish_nuget: true
  include_nuget_references: true
  
cache:
  - packages -> **\packages.config
  
before_build:
  - cmd: nuget restore
  
deploy:
  - provider: NuGet
    api_key:
      secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
    skip_symbols: false
    artifact: /.*\.nupkg/

  - provider: GitHub
    release: Release_$(appveyor_build_version)
    auth_token:
      secure: YgNJFFVi7XOW0w+JC+kk+Mnk649nsyfpW9Ssnj0wPNvPaiKW8fYlEXAvYPSmQjzm
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true